services:

  resources:
    build: ./backend
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      CONNECTION_STRING: postgresql://${DATABASE_USER?err}:${DATABASE_PASSWORD?err}@${DATABASE_HOST-localhost}:${DATABASE_PORT-5432}/${DATABASE_NAME?err}
      DEBUG: ${DEBUG}

  database:
    image: postgres:11
    ports:
      - "${DATABASE_PORT-5432}:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME?err}
      POSTGRES_USER: ${DATABASE_USER?err}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD?err}
