services:

  backend:
    ports:
      - "8080:8080"

  database:
    image: postgres:11
    ports:
      - "${DATABASE_PORT-5432}:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME?err}
      POSTGRES_USER: ${DATABASE_USERNAME?err}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD?err}
